# Generated by Django 3.2.4 on 2021-06-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='doc')),
                ('song', models.FileField(upload_to='doc')),
                ('movie', models.CharField(max_length=2000)),
                ('lyrics', models.CharField(max_length=10000)),
            ],
        ),
    ]
